<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StatisticsAnalysisTool.Capture\StatisticsAnalysisTool.Capture.csproj" />
    <ProjectReference Include="..\StatisticsAnalysisTool.Linux.Core\StatisticsAnalysisTool.Linux.Core.csproj" />
    <ProjectReference Include="..\StatisticsAnalysisTool.Network\StatisticsAnalysisTool.Network.csproj" />
    <ProjectReference Include="..\StatisticsAnalysisTool.Tui\StatisticsAnalysisTool.Tui.csproj" />
  </ItemGroup>

</Project>
