<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Libpcap" Version="0.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StatisticsAnalysisTool.Abstractions\StatisticsAnalysisTool.Abstractions.csproj" />
  </ItemGroup>

</Project>
